-- 유저 테이블 생성
CREATE TABLE TETRIS_USER
(
    USER_NO      NUMBER     PRIMARY KEY,
    USER_ID  VARCHAR2(128 CHAR)  UNIQUE NOT NULL,
    PASSWORD VARCHAR2(128 CHAR)  NOT NULL,
    NICKNAME VARCHAR2(10 CHAR)   UNIQUE NOT NULL 
);

-- 기록 테이블 생성
CREATE TABLE TETRIS_SCORE
(
    SCORE_NO    NUMBER PRIMARY KEY,
    USER_NO     NUMBER NOT NULL,
    SCORE NUMBER NOT NULL,
    REPLAY BLOB,
    TIME TIMESTAMP DEFAULT SYSDATE
);

CREATE SEQUENCE TETRIS_USER_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE TETRIS_SCORE_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOCYCLE
    NOCACHE;

-- 유저 추가 하기
INSERT INTO TETRIS_USER
VALUES(TETRIS_USER_SEQ.NEXTVAL, 'TEST2', 'TEST2', 'NIK2');

-- 닉네임 변경하기
UPDATE TETRIS_USER
SET NICKNAME = 'TEST3'
WHERE USER_NO = 1;

-- 비밀번호 수정하기
UPDATE TETRIS_USER
SET PASSWORD = 'TEST3'
WHERE USER_NO = 1;

-- 해당 닉네임을 가진 사람의 수 찾기
SELECT COUNT(USER_NO) RECORDCOUNT
FROM TETRIS_USER
WHERE NICKNAME = 'TEST';

-- 해당 ID을 가진 사람의 수 찾기
SELECT COUNT(USER_NO)
FROM TETRIS_USER
WHERE USER_ID = 'TEST';

-- ID와 비밀번호가 일치하는 사용자 찾기
SELECT USER_NO, PASSWORD, NICKNAME
FROM TETRIS_USER
WHERE USER_ID = 'TEST' AND PASSWORD = 'TEST3';

-- 모두 조회
SELECT *
FROM TETRIS_USER;

SELECT *
FROM TETRIS_SCORE;

DELETE FROM TETRIS_SCORE
WHERE USER_NO = 1;

-- 기록 추가하기
INSERT INTO TETRIS_SCORE(SCORE_NO, USER_NO, SCORE, IMG_URL)
VALUES(TETRIS_SCORE_SEQ.NEXTVAL, '1', '20015', 'ASASD');

-- 모든 점수와 점수를 달성한 사람의 별명을 가져오기 (점수 순으로)
SELECT SCORE_NO, SCORE, U.NICKNAME, TIME
FROM TETRIS_SCORE S JOIN TETRIS_USER U ON S.USER_NO = U.USER_NO
ORDER BY SCORE DESC;


-- USER_NO가 1인 사람의 모든 기록 조회 하기 (점수가 높은 순으로 )
SELECT USER_NO, SCORE, TIME
FROM TETRIS_SCORE
WHERE USER_NO = 1
ORDER BY SCORE DESC;



