-- 테이블 컬럼 데이터의 기본값 설정

CREATE TABLE EX_ORDER(
    ORDER_NO NUMBER DEFAULT 0,
    ORDER_DATE DATE DEFAULT SYSDATE
);

INSERT INTO EX_ORDER VALUES(1, '2023-08-08');

INSERT INTO EX_ORDER (ORDER_DATE) VALUES (SYSDATE);
-- ORDER_NO 컬럼엔 데이터가 저장 X

INSERT INTO EX_ORDER (ORDER_NO) VALUES (2);

--DELETE TRUNCATE DROP
DELETE FROM EX_ORDER;
TRUNCATE TABLE EX_ORDER;
DROP TABLE EX_ORDER;

/*
 - SEQUENCE
 자동으로 생성되는 유일한 정수를 반환하는 데이터베이스 객체
 주로 PRIMARY KEY 값을 생성할 때 사용.
 */
 
CREATE SEQUENCE SEQ1;

-- SEQUENCE.NEXTVAL : 시퀀스의 최종값(현재값)을 리턴하고, 그 다음 값을 생성
-- SEQUENCT.CURRVAL : 시퀀스의 최종값(현재값)을 리턴

SELECT SEQ1.NEXTVAL FROM DUAL; -- DUAL : 가상 테이블
SELECT SEQ1.CURRVAL FROM DUAL;

CREATE SEQUENCE SEQ2 INCREMENT BY 2;
SELECT SEQ2.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ3 
    INCREMENT BY 2
    MINVALUE 0;
SELECT SEQ3.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ4
    INCREMENT BY 2
    START WITH 0
    MAXVALUE 10
    MINVALUE -10;
SELECT SEQ4.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ5
    INCREMENT BY 2
    START WITH 0
    MAXVALUE 10
    MINVALUE -10
    CYCLE 
    NOCACHE;
    
SELECT SEQ5.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ6
    INCREMENT BY 2
    START WITH 3
    NOCACHE;
SELECT SEQ6.NEXTVAL FROM DUAL;

CREATE SEQUENCE SEQ_PK;
CREATE TABLE EX10(
    COL1 NUMBER PRIMARY KEY,
    COL2 VARCHAR2(10)
);

INSERT INTO EX10
VALUES (SEQ_PK.NEXTVAL, 'A');

COMMIT;