CREATE TABLE EX_CONTACT(
    CONTACT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    PHONE VARCHAR2(20),
    EMAIL VARCHAR2(20)
);

CREATE SEQUENCE CONTACT_SEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 10000
    NOCYCLE
    NOCACHE;

INSERT INTO EX_CONTACT
VALUES (CONTACT_SEQ.NEXTVAL, 'AAA', '02-000-2929', 'TEST@NAVER.COM');

INSERT INTO EX_CONTACT
VALUES (CONTACT_SEQ.NEXTVAL, 'BBB', '010-5234-6949', 'SPEO@GAMIL.COM');

INSERT INTO EX_CONTACT
VALUES (CONTACT_SEQ.NEXTVAL, 'CCC', '010-3323-2228', 'BIBLE@YAHOP.COM');

SELECT *
FROM EX_CONTACT
ORDER BY CONTACT_ID DESC;

SELECT *
FROM EX_CONTACT
WHERE PHONE LIKE '010%';